version: '3.4'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6380:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9414:9411

  personapp:
    image: person-app
    build:
      context: ./person-app
      dockerfile: Dockerfile
    ports:
      - '9090:80'
      - '3505:3505'
    environment:
      - DAPR_HTTP_PORT=3505
    depends_on:
      - redis

  greeter:
    image: greeter
    build:
      context: ./greeter
      dockerfile: Dockerfile
    ports:
      - '5050:80'
      - '3506:3506'
    environment:
      - DAPR_HTTP_PORT=3506
    depends_on:
      - redis

  personapp-dapr:
    image: 'daprio/daprd:edge'
    command:
      [
        './daprd',
        '--app-id',
        'personapp',
        '--app-port',
        '80',
        '--dapr-http-port',
        '3505',
        '--components-path',
        '/components',
        '--config',
        '/config/config.yaml',
      ]
    volumes:
      - './components/:/components'
      - './config/:/config'
    depends_on:
      - personapp
    network_mode: 'service:personapp'

  greeter-dapr:
    image: 'daprio/daprd:latest'
    command:
      [
        './daprd',
        '--app-id',
        'greeter',
        '--app-port',
        '80',
        '--dapr-http-port',
        '3506',
        '--components-path',
        '/components',
        '--config',
        '/config/config.yaml',
      ]
    volumes:
      - './components/:/components'
      - './config/:/config'
    depends_on:
      - greeter
    network_mode: 'service:greeter'
