version: '3.4'
services:
  lookups:
    image: lookups
    build:
      context: ./lookups
      dockerfile: Dockerfile
    ports:
      - '5000:80'
      - '3500:3500'

  lookups-dapr:
    image: 'daprio/daprd:edge'
    command: ['./daprd', '--app-id', 'lookups', '--app-port', '5000', '--dapr-http-port', '3500']
    depends_on:
      - lookups

  caller:
    image: caller
    build:
      context: ./caller
      dockerfile: Dockerfile
    ports:
      - '5003:80'
      - '3501:3500'

  caller-dapr:
    image: 'daprio/daprd:edge'
    command: ['./daprd', '--app-id', 'caller', '--app-port', '5003', '--dapr-http-port', '3501']
    depends_on:
      - caller
