version: '3.4'
services:
  lookups:
    image: lookups
    pull_policy: build
    build:
      context: ./lookups
      dockerfile: Dockerfile
    ports:
      - '6060:80'
      - '3505:3505'
    environment:
      - DAPR_HTTP_PORT=3505

  caller:
    image: caller
    pull_policy: build
    build:
      context: ./caller
      dockerfile: Dockerfile
    ports:
      - '5050:80'
      - '3506:3506'
    environment:
      - DAPR_HTTP_PORT=3506

  lookups-dapr:
    image: 'daprio/daprd:edge'
    command: ['./daprd', '--app-id', 'lookups', '--app-port', '80', '--dapr-http-port', '3505']
    depends_on:
      - lookups
    network_mode: 'service:lookups'

  caller-dapr:
    image: 'daprio/daprd:latest'
    command: ['./daprd', '--app-id', 'caller', '--app-port', '80', '--dapr-http-port', '3506']
    depends_on:
      - caller
    network_mode: 'service:caller'
