version: '3.4'
services:
  random-messenger:
    image: random-messenger
    pull_policy: build
    build:
      context: ./random-messenger
      dockerfile: Dockerfile
    ports:
      - '3505:3505'
    environment:
      - DAPR_HTTP_PORT=3505

  listener:
    image: listener
    pull_policy: build
    build:
      context: ./listener
      dockerfile: Dockerfile
    ports:
      - '3506:3506'
    environment:
      - DAPR_HTTP_PORT=3506

  random-messenger-dapr:
    image: 'daprio/daprd:edge'
    command: ['./daprd', '--app-id', 'random-messenger', '--dapr-http-port', '3505']
    depends_on:
      - random-messenger
    network_mode: 'service:random-messenger'

  listener-dapr:
    image: 'daprio/daprd:edge'
    command: ['./daprd', '--app-id', 'listener', '--dapr-http-port', '3506']
    depends_on:
      - listener
    network_mode: 'service:listener'
